ktor:
    application:
        modules:
            - net.orangedog.revan.ApplicationKt.module
    deployment:
        port: $APP_PORT

    development: true # TODO: Set to false for production

mongodb:
    connectionString: "$MONGODB_CONNECTION_STRING"

trubar:
    import:
        wordsDir: "$TRUBAR_IMPORT_WORDS_DIR:"

admin:
    username: "$REVAN_ADMIN_USERNAME"
    password: "$REVAN_ADMIN_PASSWORD"