ktor:
    application:
        modules:
            - net.orangedog.revan.ApplicationKt.module
    deployment:
        port: $APP_PORT

    development: "$APP_DEVELOPMENT_MODE:false"

mongodb:
    connectionString: "$MONGODB_CONNECTION_STRING"

trubar:
    import:
        wordsDir: "TRUBAR_IMPORT_WORDS_PATH:"

admin:
    username: "$REVAN_ADMIN_USERNAME"
    password: "$REVAN_ADMIN_PASSWORD"